// Code generated by apikit. DO NOT EDIT.
// apikit:checksum:1a1683f952e97f1fafc9dd4dfa2f80c64eee5d1ff14c8dcc2d85191dc7da6806

package fileupload

import (
	"context"
	"fmt"
	"net/http"

	"github.com/reation-io/apikit"
	"github.com/reation-io/apikit/validator"
)

// uploadFileAPIKit wraps the UploadFile handler with HTTP request parsing and response handling
func uploadFileAPIKit(handler func(context.Context, UploadRequest) (UploadResponse, error)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var payload UploadRequest

		// Parse request parameters
		if err := parseUploadFileRequest(w, r, &payload); err != nil {
			apikit.HandleError(w, apikit.BadRequest("failed to parse request").WithCause(err))
			return
		}
		// Validate request payload
		if err := validator.StructCtx(r.Context(), &payload); err != nil {
			// Preserve structured validation errors
			if valErr, ok := err.(validator.ValidationError); ok {
				apikit.HandleError(w, apikit.UnprocessableEntity(valErr.Message).WithDetails(valErr.FieldErrors))
			} else {
				apikit.HandleError(w, apikit.UnprocessableEntity("validation failed").WithCause(err))
			}
			return
		}

		// Call the handler
		response, err := handler(r.Context(), payload)

		// Handle response (supports HttpResponse, errors, and traditional responses)
		apikit.HandleResponse(w, response, err)
	}
}

// parseUploadFileRequest parses the HTTP request into the payload struct
func parseUploadFileRequest(w http.ResponseWriter, r *http.Request, payload *UploadRequest) error {
	// Parse multipart form data
	if err := r.ParseMultipartForm(33554432); err != nil {
		return fmt.Errorf("parsing multipart form: %w", err)
	}
	// Extract parameters
	if val := r.FormValue("title"); val != "" {
		payload.Title = val
	}
	if val := r.FormValue("description"); val != "" {
		payload.Description = val
	}
	if _, header, err := r.FormFile("file"); err == nil {
		payload.File = header
	} else if err != http.ErrMissingFile {
		return fmt.Errorf("reading file 'file': %w", err)
	}
	if vals := r.Form["tags"]; len(vals) > 0 {
		payload.Tags = vals
	}

	return nil
}

// uploadMultipleFilesAPIKit wraps the UploadMultipleFiles handler with HTTP request parsing and response handling
func uploadMultipleFilesAPIKit(handler func(context.Context, MultiUploadRequest) (MultiUploadResponse, error)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var payload MultiUploadRequest

		// Parse request parameters
		if err := parseUploadMultipleFilesRequest(w, r, &payload); err != nil {
			apikit.HandleError(w, apikit.BadRequest("failed to parse request").WithCause(err))
			return
		}
		// Validate request payload
		if err := validator.StructCtx(r.Context(), &payload); err != nil {
			// Preserve structured validation errors
			if valErr, ok := err.(validator.ValidationError); ok {
				apikit.HandleError(w, apikit.UnprocessableEntity(valErr.Message).WithDetails(valErr.FieldErrors))
			} else {
				apikit.HandleError(w, apikit.UnprocessableEntity("validation failed").WithCause(err))
			}
			return
		}

		// Call the handler
		response, err := handler(r.Context(), payload)

		// Handle response (supports HttpResponse, errors, and traditional responses)
		apikit.HandleResponse(w, response, err)
	}
}

// parseUploadMultipleFilesRequest parses the HTTP request into the payload struct
func parseUploadMultipleFilesRequest(w http.ResponseWriter, r *http.Request, payload *MultiUploadRequest) error {
	// Parse multipart form data
	if err := r.ParseMultipartForm(33554432); err != nil {
		return fmt.Errorf("parsing multipart form: %w", err)
	}
	// Extract parameters
	if val := r.FormValue("title"); val != "" {
		payload.Title = val
	}
	if form := r.MultipartForm; form != nil {
		if files := form.File["files"]; len(files) > 0 {
			payload.Files = files
		}
	}

	return nil
}
