openapi: 3.0.3
info:
    title: Swagger Petstore - OpenAPI 3.0
    description: |-
        This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
        Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
        You can now help us improve the API whether it's by making changes to the definition itself or to the code.
        That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

        Some useful links:
        - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
        - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
    version: 1.0.12
paths:
    /pet:
        put:
            tags:
                - pet
            summary: Update an existing pet.
            description: |
                Update an existing pet by Id.
            operationId: updatePet
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Pet'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "422":
                    description: Unprocessable Entity
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - petstore_auth:
                    - write:pets
                    - read:pets
        post:
            tags:
                - pet
            summary: Add a new pet to the store.
            description: |
                Add a new pet to the store.
            operationId: addPet
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Pet'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "422":
                    description: Unprocessable Entity
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - petstore_auth:
                    - write:pets
                    - read:pets
    /pet/{petId}:
        get:
            tags:
                - pet
            summary: Find pet by ID.
            description: |
                Returns a single pet.
            operationId: getPetById
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Pet'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - api_key: []
                - petstore_auth:
                    - write:pets
                    - read:pets
        post:
            tags:
                - pet
            summary: Updates a pet in the store with form data.
            description: |
                Updates a pet resource based on the form data.
            operationId: updatePetWithForm
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Pet'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - petstore_auth:
                    - write:pets
                    - read:pets
        delete:
            tags:
                - pet
            summary: Deletes a pet.
            description: |
                Delete a pet.
            operationId: deletePet
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - petstore_auth:
                    - write:pets
                    - read:pets
    /pet/{petId}/uploadImage:
        post:
            tags:
                - pet
            summary: Uploads an image.
            description: |
                Upload image of the pet.
            operationId: uploadFile
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - petstore_auth:
                    - write:pets
                    - read:pets
    /pet/findByStatus:
        get:
            tags:
                - pet
            summary: Finds Pets by status.
            description: |
                Multiple status values can be provided with comma separated strings.
            operationId: findPetsByStatus
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PetListResponse'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - petstore_auth:
                    - write:pets
                    - read:pets
    /pet/findByTags:
        get:
            tags:
                - pet
            summary: Finds Pets by tags.
            description: |
                Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
            operationId: findPetsByTags
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PetListResponse'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - petstore_auth:
                    - write:pets
                    - read:pets
    /store/inventory:
        get:
            tags:
                - store
            summary: Returns pet inventories by status.
            description: |
                Returns a map of status codes to quantities.
            operationId: getInventory
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InventoryResponse'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - api_key: []
    /store/order:
        post:
            tags:
                - store
            summary: Place an order for a pet.
            description: |
                Place a new order in the store.
            operationId: placeOrder
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Order'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "422":
                    description: Unprocessable Entity
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /store/order/{orderId}:
        get:
            tags:
                - store
            summary: Find purchase order by ID.
            description: |
                For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
            operationId: getOrderById
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Order'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
        delete:
            tags:
                - store
            summary: Delete purchase order by identifier.
            description: |
                For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors.
            operationId: deleteOrder
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        ApiResponse:
            type: object
            properties:
                code:
                    type: integer
                message:
                    type: string
                type:
                    type: string
        Category:
            type: object
            properties:
                id:
                    type: integer
                    example: 1
                name:
                    type: string
                    example: Dogs
        Error:
            type: object
            properties:
                code:
                    type: string
                message:
                    type: string
        InventoryResponse:
            type: object
        Order:
            type: object
            properties:
                complete:
                    type: boolean
                id:
                    type: integer
                    example: 10
                petId:
                    type: integer
                    example: 198772
                quantity:
                    type: integer
                    example: 7
                shipDate:
                    type: string
                status:
                    type: string
                    example: approved
        Pet:
            type: object
            properties:
                category:
                    type: object
                id:
                    type: integer
                    example: 10
                name:
                    type: string
                    example: doggie
                photoUrls:
                    type: array
                    items:
                        type: string
                status:
                    type: string
                tags:
                    type: array
                    items:
                        type: object
        PetListResponse:
            type: object
        SuccessResponse:
            type: object
            properties:
                message:
                    type: string
        Tag:
            type: object
            properties:
                id:
                    type: integer
                name:
                    type: string
        User:
            type: object
            properties:
                email:
                    type: string
                    example: john@email.com
                firstName:
                    type: string
                    example: John
                id:
                    type: integer
                    example: 10
                lastName:
                    type: string
                    example: James
                password:
                    type: string
                    example: 12345
                phone:
                    type: string
                    example: 12345
                userStatus:
                    type: integer
                    example: 1
                username:
                    type: string
                    example: theUser
