package checksum

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCalculateFileChecksum(t *testing.T) {
	// Create a temporary file
	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "test.go")

	content := "package main\n\nfunc main() {}\n"
	if err := os.WriteFile(testFile, []byte(content), 0644); err != nil {
		t.Fatalf("failed to create test file: %v", err)
	}

	// Calculate checksum
	checksum, err := CalculateFileChecksum(testFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Checksum should be a 64-character hex string
	if len(checksum) != 64 {
		t.Errorf("expected checksum length 64, got %d", len(checksum))
	}

	// Verify it's all hex characters
	for _, c := range checksum {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			t.Errorf("checksum contains non-hex character: %c", c)
		}
	}

	// Calculate again - should be the same
	checksum2, err := CalculateFileChecksum(testFile)
	if err != nil {
		t.Fatalf("unexpected error on second calculation: %v", err)
	}

	if checksum != checksum2 {
		t.Errorf("checksums don't match: %s != %s", checksum, checksum2)
	}
}

func TestCalculateFileChecksum_NonExistent(t *testing.T) {
	_, err := CalculateFileChecksum("/nonexistent/file.go")
	if err == nil {
		t.Error("expected error for non-existent file")
	}
}

func TestCalculateFileChecksum_DifferentContent(t *testing.T) {
	tmpDir := t.TempDir()

	file1 := filepath.Join(tmpDir, "file1.go")
	file2 := filepath.Join(tmpDir, "file2.go")

	os.WriteFile(file1, []byte("content1"), 0644)
	os.WriteFile(file2, []byte("content2"), 0644)

	checksum1, _ := CalculateFileChecksum(file1)
	checksum2, _ := CalculateFileChecksum(file2)

	if checksum1 == checksum2 {
		t.Error("expected different checksums for different content")
	}
}

func TestExtractChecksum(t *testing.T) {
	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "generated.go")

	// Use a valid 64-character hex checksum
	content := `// Code generated by apikit. DO NOT EDIT.
// apikit:checksum:abc123def456789012345678901234567890123456789012345678901234abcd
package main
`
	os.WriteFile(testFile, []byte(content), 0644)

	checksum, err := ExtractChecksum(testFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expected := "abc123def456789012345678901234567890123456789012345678901234abcd"
	if checksum != expected {
		t.Errorf("expected checksum %q, got %q", expected, checksum)
	}
}

func TestExtractChecksum_NoChecksum(t *testing.T) {
	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "no_checksum.go")

	content := `package main

func main() {}
`
	os.WriteFile(testFile, []byte(content), 0644)

	checksum, err := ExtractChecksum(testFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if checksum != "" {
		t.Errorf("expected empty checksum, got %q", checksum)
	}
}

func TestExtractChecksum_NonExistent(t *testing.T) {
	checksum, err := ExtractChecksum("/nonexistent/file.go")
	if err != nil {
		t.Errorf("expected no error for non-existent file, got %v", err)
	}
	if checksum != "" {
		t.Errorf("expected empty checksum for non-existent file, got %q", checksum)
	}
}

func TestHasSourceChanged(t *testing.T) {
	tmpDir := t.TempDir()
	sourceFile := filepath.Join(tmpDir, "source.go")
	generatedFile := filepath.Join(tmpDir, "source_apikit.go")

	// Create source file
	sourceContent := "package main\n\nfunc main() {}\n"
	os.WriteFile(sourceFile, []byte(sourceContent), 0644)

	// Calculate checksum
	checksum, _ := CalculateFileChecksum(sourceFile)

	// Create generated file with checksum
	generatedContent := `// Code generated by apikit. DO NOT EDIT.
// apikit:checksum:` + checksum + `
package main
`
	os.WriteFile(generatedFile, []byte(generatedContent), 0644)

	// Should not have changed
	changed, err := HasSourceChanged(sourceFile, generatedFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if changed {
		t.Error("expected source to not have changed")
	}

	// Modify source file
	modifiedContent := "package main\n\nfunc main() {\n\tprintln(\"hello\")\n}\n"
	os.WriteFile(sourceFile, []byte(modifiedContent), 0644)

	// Should have changed now
	changed, err = HasSourceChanged(sourceFile, generatedFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !changed {
		t.Error("expected source to have changed")
	}
}

func TestHasSourceChanged_NoGeneratedFile(t *testing.T) {
	tmpDir := t.TempDir()
	sourceFile := filepath.Join(tmpDir, "source.go")

	os.WriteFile(sourceFile, []byte("package main"), 0644)

	// Generated file doesn't exist - should be considered changed
	changed, err := HasSourceChanged(sourceFile, "/nonexistent/file.go")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !changed {
		t.Error("expected source to be considered changed when generated file doesn't exist")
	}
}

func TestHasSourceChanged_NoSourceFile(t *testing.T) {
	tmpDir := t.TempDir()
	generatedFile := filepath.Join(tmpDir, "generated.go")

	os.WriteFile(generatedFile, []byte("package main"), 0644)

	// Source file doesn't exist - should return error
	_, err := HasSourceChanged("/nonexistent/source.go", generatedFile)
	if err == nil {
		t.Error("expected error when source file doesn't exist")
	}
}

func TestChecksumFormat(t *testing.T) {
	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "test.go")

	os.WriteFile(testFile, []byte("test content"), 0644)

	checksum, err := CalculateFileChecksum(testFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Verify checksum is lowercase hex
	if strings.ToLower(checksum) != checksum {
		t.Error("expected checksum to be lowercase")
	}

	// Verify no special characters
	if strings.ContainsAny(checksum, " \t\n\r") {
		t.Error("checksum should not contain whitespace")
	}
}

func TestExtractChecksum_MultipleLines(t *testing.T) {
	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "multi.go")

	content := `// Code generated by apikit. DO NOT EDIT.
// Some other comment
// apikit:checksum:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
// Another comment
package main
`
	os.WriteFile(testFile, []byte(content), 0644)

	checksum, err := ExtractChecksum(testFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expected := "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
	if checksum != expected {
		t.Errorf("expected checksum %q, got %q", expected, checksum)
	}
}

func TestCalculateFileChecksum_EmptyFile(t *testing.T) {
	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "empty.go")

	os.WriteFile(testFile, []byte(""), 0644)

	checksum, err := CalculateFileChecksum(testFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Empty file should still produce a valid checksum
	if len(checksum) != 64 {
		t.Errorf("expected checksum length 64, got %d", len(checksum))
	}
}

func TestCalculateFileChecksum_LargeFile(t *testing.T) {
	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "large.go")

	// Create a large file
	var builder strings.Builder
	for i := 0; i < 10000; i++ {
		builder.WriteString("// This is a comment line\n")
	}

	os.WriteFile(testFile, []byte(builder.String()), 0644)

	checksum, err := CalculateFileChecksum(testFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(checksum) != 64 {
		t.Errorf("expected checksum length 64, got %d", len(checksum))
	}
}

func TestAddChecksumToGenerated(t *testing.T) {
	content := []byte(`// Code generated by apikit. DO NOT EDIT.
package main

func main() {}
`)

	checksum := "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
	result := AddChecksumToGenerated(content, checksum)

	resultStr := string(result)

	// Should contain the checksum comment
	if !strings.Contains(resultStr, "// apikit:checksum:"+checksum) {
		t.Error("result should contain checksum comment")
	}

	// Checksum should be after DO NOT EDIT
	doNotEditIdx := strings.Index(resultStr, "DO NOT EDIT")
	checksumIdx := strings.Index(resultStr, "apikit:checksum:")

	if doNotEditIdx == -1 {
		t.Fatal("DO NOT EDIT comment not found")
	}
	if checksumIdx == -1 {
		t.Fatal("checksum comment not found")
	}
	if checksumIdx <= doNotEditIdx {
		t.Error("checksum should be after DO NOT EDIT comment")
	}
}

func TestAddChecksumToGenerated_NoDoNotEdit(t *testing.T) {
	content := []byte(`package main

func main() {}
`)

	checksum := "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
	result := AddChecksumToGenerated(content, checksum)

	resultStr := string(result)

	// Should contain the checksum comment at the beginning
	if !strings.HasPrefix(resultStr, "// apikit:checksum:"+checksum) {
		t.Error("checksum should be at the beginning when DO NOT EDIT is not found")
	}
}

func TestAddChecksumToGenerated_PreservesContent(t *testing.T) {
	content := []byte(`// Code generated by apikit. DO NOT EDIT.
package main

func main() {
	println("hello")
}
`)

	checksum := "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
	result := AddChecksumToGenerated(content, checksum)

	resultStr := string(result)

	// Should preserve original content
	if !strings.Contains(resultStr, "package main") {
		t.Error("should preserve package declaration")
	}
	if !strings.Contains(resultStr, `println("hello")`) {
		t.Error("should preserve function content")
	}
}
