package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/reation-io/apikit/openapi/builder"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	dir        string
	pattern    string
	output     string
	ignore     []string
	validation bool
)

func main() {
	rootCmd := &cobra.Command{
		Use:   "openapi",
		Short: "OpenAPI Generator CLI",
		Long:  `A command line tool for generating OpenAPI specifications from Go code using the apikit library.`,
	}

	generateCmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate OpenAPI spec from Go code",
		RunE:  runGenerate,
	}

	generateCmd.Flags().StringVarP(&dir, "dir", "d", ".", "Base directory to scan")
	generateCmd.Flags().StringVarP(&pattern, "pattern", "p", "./...", "Go file pattern to scan")
	generateCmd.Flags().StringVarP(&output, "output", "o", "openapi.yaml", "Output file path")
	generateCmd.Flags().StringSliceVarP(&ignore, "ignore", "i", []string{}, "Glob patterns to ignore (e.g. 'vendor/**', '*_test.go')")
	generateCmd.Flags().BoolVar(&validation, "validate", true, "Enable spec validation")

	rootCmd.AddCommand(generateCmd)

	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

func runGenerate(cmd *cobra.Command, args []string) error {
	// Configure builder options
	opts := []builder.Option{
		builder.WithDir(dir),
		builder.WithPattern(pattern),
		builder.WithValidation(validation),
	}

	if len(ignore) > 0 {
		opts = append(opts, builder.WithIgnorePaths(ignore...))
	}

	fmt.Printf("Initializing OpenAPI builder...\nDirectory: %s\nPattern: %s\n", dir, pattern)
	if len(ignore) > 0 {
		fmt.Printf("Ignoring: %v\n", ignore)
	}

	// create builder
	b := builder.NewBuilderWithOptions(opts...)

	// Build spec
	fmt.Println("Scanning code and building spec...")
	spec, err := b.Build()
	if err != nil {
		return fmt.Errorf("failed to build openapi spec: %w", err)
	}

	// Validate (redundant if WithValidation is true which defaults to checking internally,
	// but good to check status if builder just returns errors on validation failure.
	// builder.Build() returns error if validation fails when configured, so we are good).

	// Open output file
	outPath := output
	if !filepath.IsAbs(outPath) {
		wd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("failed to get working directory: %w", err)
		}
		outPath = filepath.Join(wd, outPath)
	}

	// Create directory if it doesn't exist
	outDir := filepath.Dir(outPath)
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Marshal to YAML
	fmt.Println("Marshaling to YAML...")
	data, err := yaml.Marshal(spec)
	if err != nil {
		return fmt.Errorf("failed to marshal spec to yaml: %w", err)
	}

	// Add header comment
	content := append([]byte("# Generated by apikit openapi generator\n# DO NOT EDIT\n"), data...)

	// Write file
	if err := os.WriteFile(outPath, content, 0644); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	fmt.Printf("Success! OpenAPI spec generated at: %s\n", outPath)
	return nil
}
